apiVersion: v1
kind: Pod
metadata:
  name: mynginx-1-create
  labels:
    devops: '18'
    company: talent
    type: create
spec:
  containers: 
  - name: nginx18
    image: nginx:1.21.1
    ports:
    - containerPort: 80
