apiVersion: v1
kind: Pod
metadata:
  name: mynginx-restartpolicy
  labels:
    devops: '18'
    company: talent
  namespace: prod
spec:
  containers:
  - name: nginx18
    image: nginx:1.19.1
    ports:
    - containerPort: 80
    resources:
      requests:
        cpu: 20m
        memory: 200Mi
      limits:
        cpu: 100m
        memory: 500Mi
  restartPolicy: Always      
