apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-test-no-replicas
  labels:
    purpose: learning
  namespace: k8
spec:
  strategy: 
   type: Recreate
  replicas: 5
  selector:
    matchLabels:
      devops: '18'
  template:
    metadata:
      name: httpd
      labels:
        devops: '18'
        company: talent
        type: create
    spec:
      containers:
      - name: httpd
        image: httpd:latest
        ports:
        - containerPort: 80

