apiVersion: v1
kind: Pod
metadata:
  name: mynginx-imagepull-ifnot
  labels:
    devops: '18'
    company: talent
  namespace: prod
spec:
  containers: 
  - name: nginx18
    image: tomcat
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 80
    resources:
      requests:
        cpu: 20m
        memory: 200Mi
      limits:
        cpu: 100m
        memory: 500Mi
  restartPolicy: Always
